# Generated by Django 5.0.1 on 2024-01-05 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='application_token',
            field=models.UUIDField(default=uuid.UUID('fece1ce0-28d6-47bd-aac1-a31952e8bf54')),
        ),
    ]
