# Generated by Django 5.0.1 on 2024-01-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error_tracker', '0003_remove_error_application_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
    ]
