# Generated by Django 5.0.1 on 2024-01-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error_tracker', '0004_rename_user_id_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='error_trace',
            new_name='error_stack',
        ),
    ]
